### ISSUE TITLE
undionly.kkpxe

### ISSUE THREAD

**Issue by angelics** [xbgmsharp/ipxe-buildweb#10]
i have trouble building undionly.kkpxe as my vmware will be using 82545em(e1000 ethernet) instead of undionly.
its fine if i use the standard build for undionly.kpxe.

the file size for undionly.kkpxe is around the size for alldrivers i had built.

**Comment by HiuChunSo** [comment]
Same problem, when build advance undionly.kpxe, it is really bigger size. How to reduce size when choose undionly from all-drivers?

**Comment by xbgmsharp** [comment]
Hello, this seem like a iPXE issue. Please post you query into the iPXE mailing list.
ipxe-buildweb only provide the option to compile without a dev environment.
``undionly.kpxe`` by default include all driver which result in a bigger file size.
