### ISSUE TITLE
Customize image configuration options: not showing on https://rom-o-matic.eu/

### ISSUE THREAD

**Issue by jbsclm** [xbgmsharp/ipxe-buildweb#19]
There used to be a section on https://rom-o-matic.eu/ to select configuration options.
The section header is still there, but there are no options showing, is this an error on the site

**Comment by xbgmsharp** [comment]
Thanks for the feedback. Not sure what happens, but it is fixed now.

**Comment by jbsclm** [comment]
Many thanks for the prompt fix.

rgds
