### ISSUE TITLE
build.fcgi is failing

### ISSUE THREAD

**Issue by rhwood** [xbgmsharp/ipxe-buildweb#21]
Standard builds are failing on rom-o-matic.eu when built from master. https://rom-o-matic.eu/build.fcgi?BINARY=ipxe.usb&BINDIR=bin&REVISION=master&DEBUG=&EMBED.00script.ipxe=&

Based on traffic on the ipxe dev mailing lists, rom-o-matic.eu needs to have either liblzma-dev (Debian package) or xz-devel (CentOS package) installed for builds to work.

**Comment by xbgmsharp** [comment]
Thanks for the feedback.
Fixed compilation is now working fine.

**Comment by rhwood** [comment]
Thank you.
