### ISSUE TITLE
 https://rom-o-matic.eu/ is down

### ISSUE THREAD

**Issue by Jacoub** [xbgmsharp/ipxe-buildweb#22]
Greetings
it's a greet job but Unfortunately for the past few days I'm trying to acces the site to build some experimental binaries the site either fails to build & nowadays it is down
kindly advise

**Comment by xbgmsharp** [comment]
Oups something is wrong. You are right. Sorry for the inconvenient.
I had to reboot the server. 
Should be fine now.

**Comment by bpenglase** [comment]
Looks to be having an issue again. FrankD in the IRC channel pointed out the 500 error:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

**Comment by xbgmsharp** [comment]
Fixed
