### ISSUE TITLE
Parameters: DEBUG = Empty

### ISSUE THREAD

**Issue by steverweber** [xbgmsharp/ipxe-buildweb#24]
i'm creating a build and set some debug options... 
Wondering if they are being set because... when I force a build error I see:
```
Build log:
Path: 
Parameters: 
  BINARY = ipxe.iso
  BINDIR = bin
  DEBUG = 
  EMBED.00script.ipxe = 
  REVISION = master
  dhcp.h/PXEBS_END_TIMEOUT_SEC: = 0
  dhcp.h/PXEBS_MAX_TIMEOUT_SEC: = 0
...
```

**Comment by xbgmsharp** [comment]
Correct i can reproduce the issue. I will take a look at it.

**Comment by steverweber** [comment]
thanks. :)

**Comment by xbgmsharp** [comment]
Please test should be fixed.

**Comment by steverweber** [comment]
sorry don't really have the time to test.

since you are developer, if it works it likely works :)
