### ISSUE TITLE
internal server error ipxe webbuild

### ISSUE THREAD

**Issue by Elementelist** [xbgmsharp/ipxe-buildweb#27]
Hi,

I can't create any images through the web interface.
It gives me an internal server error when i try to generate a image.
Is it not working or is it just me?
Thanks in advance and many thanks for this easy tool.

Dave

**Comment by xbgmsharp** [comment]
Hi,
Sorry about that. I had to reboot the server yesterday.
Should be fine now. Please re-test.

**Comment by Elementelist** [comment]
Its working again.
thank you very much!!
