### ISSUE TITLE
Add ability to refresh local Git repo

### ISSUE THREAD

**Issue by mrjrt** [xbgmsharp/ipxe-buildweb#29]
I'm not sure how this is meant to work, but I'm reliant ATM on the RoM as I don't have a suitable build machine, and a bug fix has just (2 hours ago as of posting this) gone into the Git repo that I need, but I'm not offered that revision, nor any way to trigger a pull or get it to use a fresh clone...

So how does the build repo get updated? ...and if it's not every build, what is the update latency, and can we trigger a manual refresh?

**Comment by xbgmsharp** [comment]
The local git repository is updated every 2 hours via crontab. The last updated happened at 11am GMT, 12 minutes ago.
You can not trigger a manual refresh.

**Comment by xbgmsharp** [comment]
The local git repository is updated every 2 hours via crontab.
The NICS driver and config options are refresh every hour.
If you need a more up to date repository, you can safely compile it manually or install ipxe-buildweb
