### ISSUE TITLE
ISO build fail on line 223

### ISSUE THREAD

**Issue by maxymx** [xbgmsharp/ipxe-buildweb#31]
HI ALL
choose .ISO and build, fail on line 233
"make" unexpectedly returned exit value 2 at /var/www/ipxe-buildweb/build.fcgi line 233
please help

**Comment by copinux** [comment]
HI, me too exactelly like me...
"make" unexpectedly returned exit value 2 at /var/www/ipxe-buildweb/build.fcgi line 233

PLEASE HELP !!! thanks

**Comment by dark26** [comment]
Bonjour,

Same problem here :+1: 

Build failed:
"make" unexpectedly returned exit value 2 at /var/www/ipxe-buildweb/build.fcgi line 233

Can someone help us ?

Thanks in advance

Dark26

**Comment by mgiesen** [comment]
Same problem here.
"make" unexpectedly returned exit value 2 at /var/www/ipxe-buildweb/build.fcgi line 233

**Comment by maxymx** [comment]
Default master (recommended) 3df5 
can work, newer can not

**Comment by xbgmsharp** [comment]
It seem to be related to 
https://git.ipxe.org/ipxe.git/commit/0a20373a2fb78622043277b4774676c55bbea22b

**Comment by xbgmsharp** [comment]
The issue is now fixed, I did a local commit to update the Makefile in order to ignore the warning.
In parallel, I contacted the author of the commit and see if we could avoid the warning.

```
commit d8a61d7db56f975dc6669c2a7265d49bbcdb1392
Author: xbgmsharp 
Date:   Tue Apr 5 12:52:24 2016 +0200

    Temporaly fixed issue #31 of rom-o-matic Warning.
```

**Comment by xbgmsharp** [comment]
The author commit a fixed and will be apply when approve. Then I will revert my local fixed.

**Comment by mgiesen** [comment]
Thanks, it works.

**Comment by xbgmsharp** [comment]
Applied; into main iPXE git repository  http://git.ipxe.org/ipxe.git/commitdiff/ffd959a
