### ISSUE TITLE
Advanced .rom download doesn't recognize Marvell 88E8056 vendor/device

### ISSUE THREAD

**Issue by klui2k1** [xbgmsharp/ipxe-buildweb#33]
I needed to get an iPXE flashable ROM through the Advanced radio button but the website does not recognize vendor 11AB, device 4364 when I click on "Proceed >>." The error "Invalid or Unsupported pci_vendor_code or pci_device_code" is displayed. If I click "Save buildcfg" and click on the URL, the site builds and allows me to download the ROM file. https://www.rom-o-matic.eu/build.fcgi?BINARY=11ab4364.rom&BINDIR=bin&REVISION=master&DEBUG=&EMBED.00script.ipxe=&

Earlier I downloaded all the drivers in a bootable ISO file and it works for the NIC in question, so the vendor/device combination should work.

**Comment by xbgmsharp** [comment]
Should be fix by pull request #32.

**Comment by klui2k1** [comment]
It works now. Thank you.
