### ISSUE TITLE
The web app still goes 500 Internal server error

### ISSUE THREAD

**Issue by phatlaur** [xbgmsharp/ipxe-buildweb#41]
During the issue with the lack of space on the server (reported and allegedly fixed here https://github.com/xbgmsharp/ipxe-buildweb/issues/40), the server also started to not show build configuration options or load NIC dropdown options and if Build was pressed, it was returning 500 Internal server error.

Issue 40 (the lack of space) is claimed as fixed, but the problem with the options loading and internal server error are still happening. Please fix :)

**Comment by xbgmsharp** [comment]
The space issue now fix. However still wondering was it causing this.

**Comment by phatlaur** [comment]
It looks like you managed to figure out the problem, because it's working since you replied here.
Thanks for fixing it!
