### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by nguyentumine** [xbgmsharp/ipxe-buildweb#46]
Hi, The server is experiencing problems, hopefully it will be fixed soon. Thanks!

https://rom-o-matic.eu/build.fcgi?BINARY=ipxe.kkkpxe&BINDIR=bin&REVISION=master&DEBUG=&EMBED.00script.ipxe=%23%21ipxe%0Aset%20legacy%20true&general.h/CONSOLE_CMD:=1&console.h/CONSOLE_FRAMEBUFFER:=1&branding.h/PRODUCT_NAME=AIO%20Boot&

> **Internal Server Error**
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator, webmaster@rom-o-matic.eu and inform them of the time the error occurred, and anything you might have done that may have caused the error.
> 
> More information about this error may be available in the server error log.

**Comment by xbgmsharp** [comment]
Fix, maintenance reboot on the server.
