### ISSUE TITLE
Revisio 2fb70 iPXE build.fcgi fails - Use git revision 2bb4ec

### ISSUE THREAD

**Issue by desrod** [xbgmsharp/ipxe-buildweb#50]
Here is an example of one of the build failures: 
https://pastebin.ubuntu.com/26397612/

This is grave, as every tool that calls out to rom-o-matic to retrieve PXE images now fails. I'll try to pull the source and see if I can't fix that up, but this is a blocker at the moment. 

Thanks for your attention to this!

**Comment by xbgmsharp** [comment]
There seem to be some issue in the ipxe code. I am able to build using revision 1b67a and fb6.
gpxe is not supported and was never avaiable on rom-o-matic.eu.
Please try to identify which commit generate the error and report to iPXE.
```
  [BUILD] bin/lan78xx.o
In file included from include/string.h:21:0,
                 from drivers/net/ena.c:27:
drivers/net/ena.c: In function 'ena_probe':
arch/x86/include/bits/string.h:95:30: error: 'feature' may be used uninitialized in this function [-Werror=maybe-uninitialized]
drivers/net/ena.c:579:21: note: 'feature' was declared here
cc1: all warnings being treated as errors
make: *** [bin/ena.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/var/tmp/ipxe-build/ipxe-build-Y0QqvY/src'
"make" unexpectedly returned exit value 2 at /var/www/ipxe-buildweb/build.fcgi line 233
```

**Comment by desrod** [comment]
We used to point to 'http://rom-o-matic.net/gpxe/gpxe-1.0.1/contrib/rom-o-matic/build.php', which was briefly relocated to rom-o-matic.eu, and appeared to continue to work. 

However now, both resources are gone, and we are unable to build an image with the same options as the previous tool using build.fcti on .eu, for example the following options: 

```
PRODUCT_SHORT_NAME=gPXE
CONSOLE_PCBIOS=on
BANNER_TIMEOUT=20
NET_PROTO_IPV4=on
COMCONSOLE=0x3F8
COMSPEED=115200
COMDATA=8
COMPARITY=0
COMSTOP=1
DOWNLOAD_PROTO_TFTP=on
DNS_RESOLVER=on
NMB_RESOLVER=off
IMAGE_ELF=on
IMAGE_NBI=on
IMAGE_MULTIBOOT=on
IMAGE_PXE=on
IMAGE_SCRIPT=on
IMAGE_BZIMAGE=on
IMAGE_COMBOOT=on
AUTOBOOT_CMD=on
NVO_CMD=on
CONFIG_CMD=on
IFMGMT_CMD=on
IWMGMT_CMD=on
ROUTE_CMD=on
IMAGE_CMD=on
DHCP_CMD=on
SANBOOT_CMD=on
LOGIN_CMD=on
```
Is there another way to achieve the same result, without significant retooling or creating our own self-hosted version internally?

**Comment by xbgmsharp** [comment]
gPXE is deprecated and not maintain anymore, switch to iPXE, http://ipxe.org/faq
I own rom-o-matic.eu not rom-o-matic.net
iPXE provide way more option and you should start from starch, most would be the same.

**Comment by MacakPasko** [comment]
Hi,
I have the same problem as desrod. Unable to generate kpxe file for day's now. 
What ever I do, there is always the same error message:
"make" unexpectedly returned exit value 2 at /var/www/ipxe-buildweb/build.fcgi line 233
Thank's

**Comment by xbgmsharp** [comment]
Only the git revision fro commit failed due to ipxe. 
https://git.ipxe.org/ipxe.git/commit/2fb70e8b32244e25ca3f43518b580fe0a54536d2. 
Use git revision 2bb4ec.
https://git.ipxe.org/ipxe.git/commit/2bb4ec1f54af11f51f6f064c0086b6b80be2dcd2

**Comment by NiKiZe** [comment]
Latest (official) builds of iPXE can be found at http://boot.ipxe.org which might be helpful if no modifications is needed.

Latest commit 70189a8e4 works fine to build locally for me
@xbgmsharp can you reproduce this locally (not on the web) and what is the best way to replicate the web build environment (to get same version of gcc and glibc, other headers, etc)?

@mcb30 just a heads up of new build error in some envs
```
In file included from include/string.h:21:0,
                 from drivers/net/ena.c:27:
drivers/net/ena.c: In function 'ena_probe':
arch/x86/include/bits/string.h:95:30: error: 'feature' may be used uninitialized in this function [-Werror=maybe-uninitialized]
drivers/net/ena.c:579:21: note: 'feature' was declared here
```

**Comment by xbgmsharp** [comment]
I tested the ipxe git repo yesterday, and was able to replicate the build issue. I jsut re-try and same issue. Is this link a to specific version of `gcc version 4.7.2 (Debian 4.7.2-5)` or something? 
```
git clone https://git.ipxe.org/ipxe.git
cd ipxe/src
make
  [BUILD] bin/ena.o
In file included from include/string.h:21:0,
                 from drivers/net/ena.c:27:
drivers/net/ena.c: In function 'ena_probe':
arch/x86/include/bits/string.h:95:30: error: 'feature' may be used uninitialized in this function [-Werror=maybe-uninitialized]
drivers/net/ena.c:579:21: note: 'feature' was declared here
cc1: all warnings being treated as errors
make: *** [bin/ena.o] Error 1
```

As you can see the ena driver generate compile error, https://git.ipxe.org/ipxe.git/commit/2fb70e8b32244e25ca3f43518b580fe0a54536d2
```
Since commit 
commit 2fb70e8b32244e25ca3f43518b580fe0a54536d2
Author: Michael Brown <mcb30@ipxe.org>
Date:   Mon Jan 8 13:21:40 2018 +0000

    [ena] Add driver for Amazon ENA virtual function NIC
    
    Signed-off-by: Michael Brown <mcb30@ipxe.org>
```

**Comment by mcb30** [comment]
On 17/01/18 08:50, xbgmsharp wrote:
> I tested the ipxe git repo yesterday, and was able to replicate the 
> build issue. I jsut re-try and same issue. Is this link a to specific 
> version of |gcc version 4.7.2 (Debian 4.7.2-5)| or something?
> 
> |git clone https://git.ipxe.org/ipxe.git cd ipxe/src make [BUILD] 
> bin/ena.o In file included from include/string.h:21:0, from 
> drivers/net/ena.c:27: drivers/net/ena.c: In function 'ena_probe': 
> arch/x86/include/bits/string.h:95:30: error: 'feature' may be used 
> uninitialized in this function [-Werror=maybe-uninitialized] 
> drivers/net/ena.c:579:21: note: 'feature' was declared here cc1: all 
> warnings being treated as errors make: *** [bin/ena.o] Error 1 |

Thanks for the detailed report.  It's a compiler bug: there is no way 
that variable can be unused uninitialised, but the optimiser in that 
version of gcc seems to be unable to prove this.

I'm spinning up a Debian Wheezy VM to try out fixes.

Thanks,

Michael

**Comment by xbgmsharp** [comment]
I successfully build the latest iPXE using Debian Stretch using `gcc version 6.3.0 20170516 (Debian 6.3.0-18)`. It's a compiler bug on Debian Wheezy.

**Comment by mcb30** [comment]
On 17/01/18 10:49, Michael Brown wrote:
> Thanks for the detailed report.  It's a compiler bug: there is no way 
> that variable can be unused uninitialised, but the optimiser in that 
> version of gcc seems to be unable to prove this.
> 
> I'm spinning up a Debian Wheezy VM to try out fixes.

Should now be fixed:

   http://git.ipxe.org/ipxe.git/commitdiff/fbe8c52

Michael

**Comment by xbgmsharp** [comment]
Confirmed, All good, it works, thanks.
