### ISSUE TITLE
Out of Disk Space

### ISSUE THREAD

**Issue by humm3r1** [xbgmsharp/ipxe-buildweb#52]
Hi,

Seems you are out of disk space in /var/tmp on rom-o-matic.eu ;)
Would you mind clearing up any room if possible? I'm also going to investigate hosting my own for building off of.

Build failed:

"git" unexpectedly returned exit value 1 at /var/www/ipxe-buildweb/build.fcgi line 609

Build log:
Temporary git directory: /var/tmp/ipxe-build/ipxe-build-ilwQw4
Temporary working tree: /var/tmp/ipxe-build/ipxe-build-ADLRAV
Cloning git tree from /var/tmp/ipxe/.git...
/var/tmp/ipxe-build/ipxe-build-ilwQw4/refs/heads: No space left on device
"git" unexpectedly returned exit value 1 at /var/www/ipxe-buildweb/build.fcgi line 609

**Comment by xbgmsharp** [comment]
Fixed. a lot of build lately.
