### ISSUE TITLE
https://rom-o-matic.eu/ is down

### ISSUE THREAD

**Issue by konradb90** [xbgmsharp/ipxe-buildweb#54]
Currently https://rom-o-matic.eu/ is down.

Could you fix the problem?

Thank you!

**Comment by chrisiaut** [comment]
@xbgmsharp is this known?

**Comment by xbgmsharp** [comment]
Yes just payed new credit. Should be back up soon. Cloud service are not free...

**Comment by c0deright** [comment]
Down again

**Comment by xbgmsharp** [comment]
Did not renew the domain. please use a local docker image.

**Comment by benjaoming** [comment]
Sad to hear that, was appreciated :(

**Comment by habetsm** [comment]
Agree it is a shame this is gone.

**Comment by chrisiaut** [comment]
It is a shame but anyone with docker can self-host it in under a minute

```
docker pull xbgmsharp/ipxe-buildweb
docker run  -d --name ipxe  \
	--publish 8080:80 \
	--name ipxe-buildweb \
	xbgmsharp/ipxe-buildweb
```

**Comment by rswinney99** [comment]
I have docker desktop on windows. I have tried the above commands and I get the webpage for the ipxe image generator but when I try to build the ipxe image I get an internal server error. What am I missing?

**Comment by Barborica-Alexandru** [comment]
I am also getting an internal server error with the docker image
