### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by leasekvm** [xbgmsharp/ipxe-buildweb#56]
Hello,

when i click"proceed" on your demo site

show me 👍 

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@rom-o-matic.eu and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by ferfebles** [comment]
Same error while using docker image

**Comment by JimLin-Qcttw** [comment]
edit /var/www/ipxe-buildweb/install.sh of your ipxe docker
add IdelTimeout BuysTimeout IPCCommTimeout to fcgid.conf

**Comment by JimLin-Qcttw** [comment]
edit /var/www/ipxe-buildweb/install.sh of your ipxe docker
add IdelTimeout BuysTimeout IPCCommTimeout MaxRequestLen to fcgid.conf and restart your ipxe docker.
![image](https://user-images.githubusercontent.com/28556452/70875632-89efe080-1ff1-11ea-90c0-7592629cddb3.png)

**Comment by MarcDoughty** [comment]
Can confirm that the builds time-out on some machines, and that this fixes it.

**Comment by xbgmsharp** [comment]
fix with 2133861079fc835bc6cf6bb8c8e6c9ee61fb3467
