### ISSUE TITLE
http://rom-o-matic.eu not working

### ISSUE THREAD

**Issue by ferfebles** [xbgmsharp/ipxe-buildweb#57]
Hi, I've been using your project the last four years because it's much more convenient than building ipxe by hand.

But when I try to connect to http://rom-o-matic.eu it says "rom-o-matic.eu’s server IP address could not be found."

I tried running my own service using docker, but even with the standard build options it gives an error 500.

Should I try to build ipxe by hand, or will http://rom-o-matic.eu be up soon?

**Comment by NiKiZe** [comment]
duplicate of #54, especially:

> Did not renew the domain. please use a local docker image.

_Originally posted by @xbgmsharp in https://github.com/xbgmsharp/ipxe-buildweb/issues/54#issuecomment-552907665_

**Comment by donnydavis** [comment]
If people are using this please consider donating. 
I am happy to be the first, please send me a link or post it here. rom-o-matic is valuable. 

Also please contact me to rehost rom-o-matic. donny@fortnebula.com

**Comment by rswinney99** [comment]
I would donate to this as well

**Comment by lps-rocks** [comment]
I've stood up https://rom-o-matic.dev - I intend on hosting this indefinitely. I use it as a tool myself and as long as it's not abused, I will continue to host it. 

I understand people's skepticism in running binary builds created by other systems. Especially those created by an 'unofficial' website. I took as many precautions as possible to ensure longevity, security, and stability of the build. 

- The TLD (.dev) was chosen as it is a "secure" TLD - [More Info](https://get.dev/)
- The Domain was registered using a registrar that supports and enforces 2FA and supports DNSSEC
- DNSSEC is enabled on the domain and registrar
- CloudFlare is used as a front-end on an account with 2FA enabled
- CloudFlare is configured with Forced Strict SSL encryption is enabled
- SSL is facilitated to the docker container using an nginx reverse proxy container
- HSTS is enabled using HTTPS headers for the domain as well as the www. subdomain (as well as all subdomains) - This is partially redundant since the .dev TLD is in the HSTS preload list in all Chromium based browsers.
- The build system is hosted on robust hardware that does perform other functions but is properly segmented and virtualized
- The build system is using the preferred [docker image](https://hub.docker.com/r/xbgmsharp/ipxe-buildweb) .
- The build system is monitored by [watchtower](https://github.com/containrrr/watchtower) so any updates to the docker image are deployed automatically.
- The build system is automatically rebuilt every night to ensure stability and using the latest build packages.

**Comment by robinsmidsrod** [comment]
@lps-rocks I've added this updated link to rom-o-matic back to the Tools page on networkboot.org. Great work!

**Comment by rswinney99** [comment]
That's awesome! Thanks for doing that. 

I still get an error when trying to build a 64 bit .efi rom. I got the same error using docker on my own though. Anyone else get the same result?

See error:

Build failed:

"make" unexpectedly returned exit value 2 at /var/www/ipxe-buildweb/build.fcgi line 630.


Build log:
Path: 
Parameters: 
  BINARY = ipxe.efi
  BINDIR = bin-x86_64-efi
  DEBUG = 
  EMBED.00script.ipxe = 
  REVISION = master
  general.h/PXE_STACK: = 1
Binary: ipxe.efi
Binary directory: bin-x86_64-efi
Revision: master
Canonicalising revision master...
Canonical revision: ebff21a515f948848e4cb7e332bb6438aafdeb57
Creating temporary directories...
Temporary git directory: /var/tmp/ipxe-build/ipxe-build-jJCNHj
Temporary working tree: /var/tmp/ipxe-build/ipxe-build-eECtT7
Cloning git tree from /var/tmp/ipxe/.git...
Finding closest cached binaries for ebff21a515f948848e4cb7e332bb6438aafdeb57...
fatal: No names found, cannot describe anything.
fatal: cannot describe 'ebff21a515f948848e4cb7e332bb6438aafdeb57'
Found no cached binaries
Checking out revision ebff21a515f948848e4cb7e332bb6438aafdeb57...
Building cacheable binaries...
make: Entering directory `/var/tmp/ipxe-build/ipxe-build-eECtT7/src'
rm -f  bin-x86_64-efi/*.*  bin-x86_64-efi/.certificate.* bin-x86_64-efi/.certificates.* bin-x86_64-efi/.private_key.* bin-x86_64-efi/errors	 bin-x86_64-efi/NIC	 ./util/zbin ./util/elf2efi32 ./util/elf2efi64 ./util/efirom ./util/efifatbin ./util/iccfix ./util/einfo TAGS bin-x86_64-efi/symtab
  [PARSEROM]

**Comment by lps-rocks** [comment]
@rswinney99 - can you share your buildcfg link?

**Comment by rswinney99** [comment]
I'm just going to advanced then EFI PXE bootstrap 64-bit (.efi) then I leave all options default except I check 
PXE support:
PXE_STACK, PXE stack in iPXE - you want this

Like I said, it does it when I self host as well.

**Comment by lps-rocks** [comment]
So, PXE_STACK + EFI do not work together, see:

https://forum.ipxe.org/showthread.php?tid=8024

**Comment by rswinney99** [comment]
Interesting. Thanks for the info. Everything works correctly without the option and my boot process is successful, I'd just formed a habit of using that option in the past. 

Again thanks for hosting https://rom-o-matic.dev it's great to have that option back.

**Comment by donnydavis** [comment]
@rswinney99 I see no donate button. This is depressing. 

Also if you need compute resources, I own a cloud company and I am happy to donate compute cycles and object storage to help with the workload. 
I find rom-o-matic immensely useful, so any way I can help I am happy to.

**Comment by ferfebles** [comment]
Thanks @lps-rocks. I've been building ipxe by hand since november, but it's great to have ipxe-buildweb up again. I'm sure that people new to ipxe will find it very useful, as It was for myself.

Thanks @xbgmsharp for your previous work. Perhaps could be useful to place a link to the new URL in the readme of this project.

I'm closing this issue with a happy smile in my face!.

**Comment by sebaxakerhtc** [comment]
An alternative from my side:  http://ipxe.pcserviceburgas.com
It's just for me, but if you want - use it :)

**Comment by MaxPeal** [comment]
@donnydavis it would be sensible to also host a instance at youre cloud company, to have a alternative.
(mybe like up a new instance for earch user? and for transparency host the cloud-init config also on github?)

the host form @lps-rocks is not working at the moment.
URL https://rom-o-matic.dev/build.fcgi?BINARY=ipxe.iso&BINDIR=bin&REVISION=master&DEBUG=&EMBED.00script.ipxe=&

Build failed:

Could not dup tarfh: Bad file descriptor

Build log:
Path:
Parameters:
BINARY = ipxe.iso
BINDIR = bin
DEBUG =
EMBED.00script.ipxe =
REVISION = master
Binary: ipxe.iso
Binary directory: bin
Revision: master
Canonicalising revision master...
Canonical revision: 98d49e460a27f74212aab2d6b5eef1143c7a8e37
Creating temporary directories...
Temporary git directory: /tmp/ipxe/build/ipxe-build-InipJd
Temporary working tree: /tmp/ipxe/build/ipxe-build-WHqnht
Cloning git tree from /tmp/ipxe/source/.git...
Finding closest cached binaries for 98d49e460a27f74212aab2d6b5eef1143c7a8e37...
Found cached binaries in ipxe-build/cached/bin/98d49e460a27f74212aab2d6b5eef1143c7a8e37.gz at distance 0
Opening binary tarball /tmp/ipxe/cache/98d49e460a27f74212aab2d6b5eef1143c7a8e37-bin.tar.gz...
Opened binary tarball /tmp/ipxe/cache/98d49e460a27f74212aab2d6b5eef1143c7a8e37-bin.tar.gz...
Checking out revision 98d49e460a27f74212aab2d6b5eef1143c7a8e37...
Identifying timestamp for commit 98d49e460a27f74212aab2d6b5eef1143c7a8e37...
Setting timestamps to Tue Jul 7 13:08:05 2020...
Unpacking binary tarball /tmp/ipxe/cache/98d49e460a27f74212aab2d6b5eef1143c7a8e37-bin.tar.gz...
Could not dup tarfh: Bad file descriptor
Filehandle STDIN reopened as STDOUT only for output at /var/www/rom-o-matic/build.fcgi line 749.

**Comment by lps-rocks** [comment]
I've enabled issues on my fork. Hrm, bad file descriptor... I'ma have to check that one out.

**Comment by lps-rocks** [comment]
Looks like the docker container got fubar'd - I'll have to add a check to the monitoring service i have that makes sure builds are actually working. Thanks for the heads up.

**Comment by donnydavis** [comment]
I know everyone wants to use docker for everything these days - but a good ole fashioned VM still works pretty well IMO. 
Code for how to build a cloud ready image is here - https://gitlab.com/fortnebula/ipxe-web

I have the image building and seems to work properly. Just need to function test it and see whats busted.

**Comment by samthelion** [comment]
> I know everyone wants to use docker for everything these days - but a good ole fashioned VM still works pretty well IMO.
> Code for how to build a cloud ready image is here - https://gitlab.com/fortnebula/ipxe-web
> 
> I have the image building and seems to work properly. Just need to function test it and see whats busted.
> https://ipxe.fortnebula.com/

I'd like to know how to deploy that. I can't find any documentation. Please update the README.

**Comment by donnydavis** [comment]
@samthelion is this better - https://gitlab.com/fortnebula/ipxe-web/-/blob/master/README.md

**Comment by samthelion** [comment]
> @samthelion is this better - https://gitlab.com/fortnebula/ipxe-web/-/blob/master/README.md

That's way better! I still wonder if there's a way to build the image myself tho. Sorry if that's an obvious thing but i'm a newbie ;)

**Comment by donnydavis** [comment]
Ok, its updated. If you have any problems with it please open an issue https://gitlab.com/fortnebula/ipxe-web/-/issues

**Comment by samthelion** [comment]
> Ok, its updated. If you have any problems with it please open an issue https://gitlab.com/fortnebula/ipxe-web/-/issues

Cool! Thanks.
