### ISSUE TITLE
Build failed "git" unexpectedly.....

### ISSUE THREAD

**Issue by rswinney99** [xbgmsharp/ipxe-buildweb#61]
Have the docker image up and running but having an issue trying the build an ipxe image. The following log is displayed after clicking the Proceed button.

Build failed:

"git" unexpectedly returned exit value 128 at /var/www/ipxe-buildweb/build.fcgi line 591.

Build log:
Path: 
Parameters: 
  BINARY = ipxe.efi
  BINDIR = bin-x86_64-efi
  DEBUG = 
  EMBED.00script.ipxe = 
  REVISION = master
Binary: ipxe.efi
Binary directory: bin-x86_64-efi
Revision: master
Canonicalising revision master...
fatal: Not a git repository: '/var/tmp/ipxe/.git'
"git" unexpectedly returned exit value 128 at /var/www/ipxe-buildweb/build.fcgi line 591.

The options under "Choose a NIC type" and "Customize image configuration options" are missing

![Capture](https://user-images.githubusercontent.com/59094588/72933577-3aeb4880-3d1f-11ea-987f-5aff4aa7f351.JPG)

Any guidance on where to look from here?

**Comment by DancingDolphins** [comment]
same here

**Comment by xbgmsharp** [comment]
This seem to be the error:
`fatal: Not a git repository: '/var/tmp/ipxe/.git'`

Should be fix with 4bee4586be8b31699c43f2ea717df074f8dc99a6
