### ISSUE TITLE
iPXE 1.0.0 build always

### ISSUE THREAD

**Issue by sebaxakerhtc** [xbgmsharp/ipxe-buildweb#65]
Doesn't matter which revision you choose from web interface - still build old version of iPXE 1.0.0
If there's a way to use latest images or to build choosen revision?
Or how we can update cached binaries?

**Comment by NiKiZe** [comment]
iPXE version comes from git tags, but if I remember correctly git is not available to the build process itself. And in that case the generic 1.0.0+ version is shown even if it is the latest code.

**Comment by sebaxakerhtc** [comment]
> in that case the generic 1.0.0+ version is shown even if it is the latest code

Hope it is

**Comment by xbgmsharp** [comment]
https://github.com/xbgmsharp/ipxe-buildweb/blob/master/install.sh#L38

**Comment by sebaxakerhtc** [comment]
> https://github.com/xbgmsharp/ipxe-buildweb/blob/master/install.sh#L38

Thank you for the project!
Yes, i reviewed a whole code, but still can't find why the version of builded images 1.0.0+
It's better to show a real version isn't it?

**Comment by xbgmsharp** [comment]
iPXE does not manage version, it is always the generic 1.0.0+ version. There are very few tags over the +10 years.
The important part is the git commit in the versioning as per https://ipxe.org/cfg/version and
https://dox.ipxe.org/version_8c.html#a36f8da1d7cefa8b6bf0fd6509cd0162a

You might be able to change it:
https://github.com/ipxe/ipxe/blob/5aee6b81d73086fd4a48f2280043d7b5518b3303/src/Makefile#L210

**Comment by sebaxakerhtc** [comment]
> iPXE does not manage version, it is always the generic 1.0.0+ version. There are very few tags over the +10 years.

Yes, it is. I understand, the code still latest, only cosmetic one is when you build it from source - it shows the 1.21.1+(tag) and revision, but from ipxe-buildweb is always 1.0.0+
Thats why people think is OLD.  
![1](https://user-images.githubusercontent.com/32651506/196889173-e699830b-a902-45ec-a5fd-b43d6b132658.png)
![2](https://user-images.githubusercontent.com/32651506/196889177-b33b7149-b6ef-45b3-ace8-adeefc9ceafc.png)

**Comment by NiKiZe** [comment]
Again if you don't have git available and a full clone then the version is not correct.

Are you building with a full git checkout? And is the git command available and found by make?

If this works correctly you will currently get the 1.21.1+.... Version tag as in @sebaxakerhtc but something seems to make this fail in buildweb?

**Comment by sebaxakerhtc** [comment]
> something seems to make this fail in buildweb?

Yes. It's a bug of ipxe-buildweb. I don't understand why issue is closed if the problem was not solved.
This project not work at all because of missing packages if you build it from source, but work if we just pull and run it.
But now the main question is why always build v1.0.0 and how can we make it to work normally.
There is a same question (as you know @NiKiZe) at the [Github Discussions of ipxe.](https://github.com/ipxe/ipxe/discussions/764)

**Comment by NiKiZe** [comment]
From the build perspective git might be a risk. So not available at build, and thus closed as "works as intended, won't fix" the issue is there but nothing that is reasonable to do anything about, or this is duplicate of other issue.

You always build master, it is good to see which version that is. But it is still the latest source, regardless of the version string ending up in the build.

**Comment by sebaxakerhtc** [comment]
> From the build perspective git might be a risk. So not available at build, and thus closed as "works as intended, won't fix" the issue is there but nothing that is reasonable to do anything about, or this is duplicate of other issue.
> 
> You always build master, it is good to see which version that is. But it is still the latest source, regardless of the version string ending up in the build.

Understand you. I will stop posting to this issue. Thank you!
