### ISSUE TITLE
Active Project? - Docker Image fails, build also fails

### ISSUE THREAD

**Issue by mediocreatmybest** [xbgmsharp/ipxe-buildweb#66]
Hi, 

Just curious if the project is still active? tried to build the container but it fails the build due to files not being found. 
The Docker image also fails due to git failing to clone the iPXE repository with a certificate error, I'm guessing the client might be old and missing certs on the docker hub. 

Thanks!

**Comment by xbgmsharp** [comment]
Hello
Long time I did not build an ipxe image but want it working. Therefor the latest commit fix the deb install using the latest LTS ubuntu image.
Also don't have any x86-64 machine.

**Comment by mediocreatmybest** [comment]
Thanks, I'll give it a shot. I did manage to get it working manually by fixing a few packages yesterday but ran into a few other issues which could be related to an NTLM proxy. I'll do a fresh pull from home and post an update. Thanks again!

**Comment by mediocreatmybest** [comment]
> Hello Long time I did not build an ipxe image but want it working. Therefor the latest commit fix the deb install using the latest LTS ubuntu image. Also don't have any x86-64 machine.

Just a quick update, I'll try get a better look this weekend, I did manage to get it built and generate an iPXE iso, so that is a good start. 
It was throwing quite a few errors up in the terminal that I wasn't able to catch, including git missing as a package, as well as errors in the install.sh and start.sh wasn't able to be found. 
I'm guessing a package may not be installed by default that previously was on the older LTS that is causing a few issues. 

Thanks again! :)

**Comment by mediocreatmybest** [comment]
Hi @xbgmsharp 

Just closing this one off so it's not dangling. I did some additional updates and merged some cleanups from another repository as well. 

https://github.com/mediocreatmybest/ROM-OH-MATIC, works quite well.

**Comment by xbgmsharp** [comment]
Checked the image in dockerhub and it is  is out of date as the github action is not running, however it does build just fine.
Happy to merge a good PR.
Docker is missing multi architecture support because syslinux is only available on amd64, https://packages.ubuntu.com/jammy/syslinux

**Comment by mediocreatmybest** [comment]
Thanks, I’ll have a look at this when I’m back home in a few weeks. 👍
